[package]
name = "stream-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5"
futures = "0.3"
pin-project-lite = "0.2"
tokio = { version = "1", features = ["io-util"] }
tokio-util = { version = "0.7", features = ["io"] }
